# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "k6SjUMivNReZGzDOa/yXHQ8zkgB27qhyucMkRRQZaJVmjBIuThMZ49y9VbvCJmfNW2jrClvncL2grIee0d6iLEKO1q3BFSVcbsXqmqCieIyF8xlxgWIz9w2OrXvlka4ubU7Mm6oZVUzlkwgjMHkkS05S+dQiR/mhCHDJ/9baytiIiJqwJjxehp6VqOZommsuWrzrM5leT8h/xnZz29YkUiquym5AHvt2uFWLxgE45O6UvPp8/Ij86HqhIYx8c4O82kzeof9GQNxnDQjbrgOLiPWUKqRas18swOO0X5OGMWfqZphKf0vwAOYihqZEz69iWf+dH3gUji8Nnnp6AJlP7rzJ0jzWejEBJ3TEMuDkixIoBJ6z4pGubYD2gYu4KqvttyO3Ti47AaBB7l+Z6rp6mK/bOoQ0Lzr8Rq0sHqzO4eaV4t1Y0L8TxrjQFBooUQRAZCVj3Bi54RP6VMcvSSm/R6vEuQcth5kvXZmOOygFJj6SSN2IYZZGeQ1me/bAp9kP9nTwyOneEbSyXnqUyxEY3+fu49UyvJjaMxVVY3Uxgd8sq4gc+bkTMe55K1s3K5j/j6o6UMpILKE+KeHZU3JpY7zqTMTDAhh4U1JqJO+pDNZzDY/4WDxNDuS0cAMWmXIZDVxol7RWlzyZQfmpp/aIrtTNwr8T6kWadMlDZPILJ+I="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
