travis:
  secure:
    BINSTAR_TOKEN: k6SjUMivNReZGzDOa/yXHQ8zkgB27qhyucMkRRQZaJVmjBIuThMZ49y9VbvCJmfNW2jrClvncL2grIee0d6iLEKO1q3BFSVcbsXqmqCieIyF8xlxgWIz9w2OrXvlka4ubU7Mm6oZVUzlkwgjMHkkS05S+dQiR/mhCHDJ/9baytiIiJqwJjxehp6VqOZommsuWrzrM5leT8h/xnZz29YkUiquym5AHvt2uFWLxgE45O6UvPp8/Ij86HqhIYx8c4O82kzeof9GQNxnDQjbrgOLiPWUKqRas18swOO0X5OGMWfqZphKf0vwAOYihqZEz69iWf+dH3gUji8Nnnp6AJlP7rzJ0jzWejEBJ3TEMuDkixIoBJ6z4pGubYD2gYu4KqvttyO3Ti47AaBB7l+Z6rp6mK/bOoQ0Lzr8Rq0sHqzO4eaV4t1Y0L8TxrjQFBooUQRAZCVj3Bi54RP6VMcvSSm/R6vEuQcth5kvXZmOOygFJj6SSN2IYZZGeQ1me/bAp9kP9nTwyOneEbSyXnqUyxEY3+fu49UyvJjaMxVVY3Uxgd8sq4gc+bkTMe55K1s3K5j/j6o6UMpILKE+KeHZU3JpY7zqTMTDAhh4U1JqJO+pDNZzDY/4WDxNDuS0cAMWmXIZDVxol7RWlzyZQfmpp/aIrtTNwr8T6kWadMlDZPILJ+I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
